name: Java CI with Maven (Java 23)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install JDK 23 manually
        run: |
          wget -O /tmp/jdk23.tar.gz https://github.com/adoptium/temurin23-binaries/releases/latest/download/OpenJDK23U-jdk_x64_linux_hotspot_23.0.0.tar.gz 
          mkdir -p $HOME/jdk23
          tar -xzf /tmp/jdk23.tar.gz -C $HOME/jdk23 --strip-components=1
          echo "$HOME/jdk23/bin" >> $GITHUB_PATH
          java -version

      - name: Set up Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Archive JAR artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: target/*.jar
